import { StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: theme.spacing.l,
    paddingTop: theme.spacing.m,
    paddingBottom: theme.spacing.m,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    ...theme.shadows.small,
  },
  addButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: "center",
  },
  headerOverline: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.text.light,
    letterSpacing: 1.2,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: theme.colors.text.primary,
    marginTop: 2,
  },
  // Summary Card Styles
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: theme.spacing.l,
    marginHorizontal: theme.spacing.l,
    marginTop: theme.spacing.m,
    marginBottom: theme.spacing.l,
    ...theme.shadows.medium,
  },
  summaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.s,
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.text.light,
    letterSpacing: 1.2,
  },
  summaryAmount: {
    fontSize: 36,
    fontWeight: "800",
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.m,
  },
  summaryDecimal: {
    fontSize: 24,
    color: theme.colors.text.secondary,
  },
  summaryFooter: {
    flexDirection: "row",
    alignItems: "center",
  },
  summaryItem: {
    flex: 1,
  },
  summaryItemLabel: {
    fontSize: 12,
    color: theme.colors.text.light,
    marginBottom: 4,
  },
  summaryItemValue: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text.primary,
  },
  summaryDivider: {
    width: 1,
    height: 30,
    backgroundColor: "#E5E7EB",
    marginHorizontal: theme.spacing.m,
  },
  // Subscription Card Styles
  subscriptionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: theme.spacing.m,
    marginHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
    flexDirection: "row",
    alignItems: "center",
    ...theme.shadows.small,
  },
  logoContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: theme.spacing.m,
  },
  logo: {
    width: 24,
    height: 24,
  },
  subscriptionInfo: {
    flex: 1,
  },
  subscriptionName: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: 4,
  },
  subscriptionCategory: {
    fontSize: 13,
    color: theme.colors.text.light,
    marginBottom: 4,
  },
  billingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  billingText: {
    fontSize: 12,
    color: "#94A3B8",
  },
  amountContainer: {
    alignItems: "flex-end",
  },
  subscriptionAmount: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text.primary,
  },
  perMonth: {
    fontSize: 12,
    color: theme.colors.text.light,
  },
  // Upcoming Payment Card Styles
  upcomingHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacing.m,
  },
  warningIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FEF3C7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: theme.spacing.m,
  },
  upcomingInfo: {
    flex: 1,
  },
  upcomingTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: 4,
  },
  upcomingSubtitle: {
    fontSize: 13,
    color: theme.colors.text.light,
  },
  upcomingFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  payNowButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  payNowText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.primary,
  },
  // Existing styles below
  spendCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: theme.spacing.l,
    marginHorizontal: theme.spacing.l,
    marginTop: theme.spacing.m,
    marginBottom: theme.spacing.l,
    ...theme.shadows.medium,
  },
  spendHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.s,
  },
  spendLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.text.light,
    letterSpacing: 1.2,
  },
  trendBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DBEAFE",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  trendText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#3B82F6",
  },
  spendAmountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: theme.spacing.m,
  },
  spendAmount: {
    fontSize: 36,
    fontWeight: "800",
    color: theme.colors.text.primary,
  },
  perMonthText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    marginLeft: 4,
  },
  statsRow: {
    flexDirection: "row",
    gap: theme.spacing.m,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: theme.spacing.m,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: theme.colors.text.light,
    letterSpacing: 1,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.text.primary,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.text.primary,
  },
  actionBadge: {
    backgroundColor: "#FEF2F2",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  actionText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#EF4444",
    letterSpacing: 0.5,
  },
  upcomingCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: theme.spacing.m,
    marginHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
    borderLeftWidth: 4,
    borderLeftColor: "#F97316",
    ...theme.shadows.small,
  },
  upcomingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacing.m,
  },
  subInfo: {
    flex: 1,
    marginLeft: theme.spacing.m,
  },
  subName: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.text.primary,
    marginBottom: 4,
  },
  subCategory: {
    fontSize: 13,
    color: theme.colors.text.light,
  },
  subPriceBlock: {
    alignItems: "flex-end",
  },
  priceText: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text.primary,
  },
  periodText: {
    fontSize: 12,
    color: theme.colors.text.light,
  },
  alertBlock: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    padding: 10,
    borderRadius: 12,
    gap: 8,
  },
  alertText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#92400E",
    flex: 1,
  },
  progressBarBg: {
    width: 60,
    height: 4,
    backgroundColor: "#FDE68A",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    width: "90%",
    backgroundColor: "#F97316",
  },
  sortRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
    marginTop: theme.spacing.m,
  },
  sortBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sortText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text.secondary,
  },
  subscriptionItem: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: theme.spacing.m,
    marginHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
    flexDirection: "row",
    alignItems: "center",
    ...theme.shadows.small,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 4,
  },
  statusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  daysLeftBadge: {
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 4,
  },
  daysLeftText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#92400E",
  },
});
